//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace PREP.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class SAPDActivityEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new SAPDActivityEntities object using the connection string found in the 'SAPDActivityEntities' section of the application configuration file.
        /// </summary>
        public SAPDActivityEntities() : base("name=SAPDActivityEntities", "SAPDActivityEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SAPDActivityEntities object.
        /// </summary>
        public SAPDActivityEntities(string connectionString) : base(connectionString, "SAPDActivityEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SAPDActivityEntities object.
        /// </summary>
        public SAPDActivityEntities(EntityConnection connection) : base(connection, "SAPDActivityEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Prep_Event> Prep_Event
        {
            get
            {
                if ((_Prep_Event == null))
                {
                    _Prep_Event = base.CreateObjectSet<Prep_Event>("Prep_Event");
                }
                return _Prep_Event;
            }
        }
        private ObjectSet<Prep_Event> _Prep_Event;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Prep_Event EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPrep_Event(Prep_Event prep_Event)
        {
            base.AddObject("Prep_Event", prep_Event);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SAPDActivityModel", Name="Prep_Event")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Prep_Event : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Prep_Event object.
        /// </summary>
        /// <param name="eventID">Initial value of the EventID property.</param>
        /// <param name="subject">Initial value of the Subject property.</param>
        /// <param name="start">Initial value of the Start property.</param>
        /// <param name="isFullDay">Initial value of the IsFullDay property.</param>
        public static Prep_Event CreatePrep_Event(global::System.Int32 eventID, global::System.String subject, global::System.DateTime start, global::System.Boolean isFullDay)
        {
            Prep_Event prep_Event = new Prep_Event();
            prep_Event.EventID = eventID;
            prep_Event.Subject = subject;
            prep_Event.Start = start;
            prep_Event.IsFullDay = isFullDay;
            return prep_Event;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 EventID
        {
            get
            {
                return _EventID;
            }
            set
            {
                if (_EventID != value)
                {
                    OnEventIDChanging(value);
                    ReportPropertyChanging("EventID");
                    _EventID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("EventID");
                    OnEventIDChanged();
                }
            }
        }
        private global::System.Int32 _EventID;
        partial void OnEventIDChanging(global::System.Int32 value);
        partial void OnEventIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Subject
        {
            get
            {
                return _Subject;
            }
            set
            {
                OnSubjectChanging(value);
                ReportPropertyChanging("Subject");
                _Subject = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Subject");
                OnSubjectChanged();
            }
        }
        private global::System.String _Subject;
        partial void OnSubjectChanging(global::System.String value);
        partial void OnSubjectChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Start
        {
            get
            {
                return _Start;
            }
            set
            {
                OnStartChanging(value);
                ReportPropertyChanging("Start");
                _Start = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Start");
                OnStartChanged();
            }
        }
        private global::System.DateTime _Start;
        partial void OnStartChanging(global::System.DateTime value);
        partial void OnStartChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> End
        {
            get
            {
                return _End;
            }
            set
            {
                OnEndChanging(value);
                ReportPropertyChanging("End");
                _End = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("End");
                OnEndChanged();
            }
        }
        private Nullable<global::System.DateTime> _End;
        partial void OnEndChanging(Nullable<global::System.DateTime> value);
        partial void OnEndChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Presentation
        {
            get
            {
                return _Presentation;
            }
            set
            {
                OnPresentationChanging(value);
                ReportPropertyChanging("Presentation");
                _Presentation = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Presentation");
                OnPresentationChanged();
            }
        }
        private Nullable<global::System.Int32> _Presentation;
        partial void OnPresentationChanging(Nullable<global::System.Int32> value);
        partial void OnPresentationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Exposure
        {
            get
            {
                return _Exposure;
            }
            set
            {
                OnExposureChanging(value);
                ReportPropertyChanging("Exposure");
                _Exposure = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Exposure");
                OnExposureChanged();
            }
        }
        private Nullable<global::System.Int32> _Exposure;
        partial void OnExposureChanging(Nullable<global::System.Int32> value);
        partial void OnExposureChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ComEvent
        {
            get
            {
                return _ComEvent;
            }
            set
            {
                OnComEventChanging(value);
                ReportPropertyChanging("ComEvent");
                _ComEvent = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ComEvent");
                OnComEventChanged();
            }
        }
        private Nullable<global::System.Int32> _ComEvent;
        partial void OnComEventChanging(Nullable<global::System.Int32> value);
        partial void OnComEventChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Attend
        {
            get
            {
                return _Attend;
            }
            set
            {
                OnAttendChanging(value);
                ReportPropertyChanging("Attend");
                _Attend = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Attend");
                OnAttendChanged();
            }
        }
        private Nullable<global::System.Int32> _Attend;
        partial void OnAttendChanging(Nullable<global::System.Int32> value);
        partial void OnAttendChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Notes
        {
            get
            {
                return _Notes;
            }
            set
            {
                OnNotesChanging(value);
                ReportPropertyChanging("Notes");
                _Notes = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Notes");
                OnNotesChanged();
            }
        }
        private global::System.String _Notes;
        partial void OnNotesChanging(global::System.String value);
        partial void OnNotesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> EnteredBy
        {
            get
            {
                return _EnteredBy;
            }
            set
            {
                OnEnteredByChanging(value);
                ReportPropertyChanging("EnteredBy");
                _EnteredBy = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EnteredBy");
                OnEnteredByChanged();
            }
        }
        private Nullable<global::System.Int32> _EnteredBy;
        partial void OnEnteredByChanging(Nullable<global::System.Int32> value);
        partial void OnEnteredByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> EnteredDate
        {
            get
            {
                return _EnteredDate;
            }
            set
            {
                OnEnteredDateChanging(value);
                ReportPropertyChanging("EnteredDate");
                _EnteredDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EnteredDate");
                OnEnteredDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _EnteredDate;
        partial void OnEnteredDateChanging(Nullable<global::System.DateTime> value);
        partial void OnEnteredDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsFullDay
        {
            get
            {
                return _IsFullDay;
            }
            set
            {
                OnIsFullDayChanging(value);
                ReportPropertyChanging("IsFullDay");
                _IsFullDay = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsFullDay");
                OnIsFullDayChanged();
            }
        }
        private global::System.Boolean _IsFullDay;
        partial void OnIsFullDayChanging(global::System.Boolean value);
        partial void OnIsFullDayChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ThemeColor
        {
            get
            {
                return _ThemeColor;
            }
            set
            {
                OnThemeColorChanging(value);
                ReportPropertyChanging("ThemeColor");
                _ThemeColor = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ThemeColor");
                OnThemeColorChanged();
            }
        }
        private global::System.String _ThemeColor;
        partial void OnThemeColorChanging(global::System.String value);
        partial void OnThemeColorChanged();

        #endregion

    
    }

    #endregion

    
}
